Controllers/MusicController.cs
using Microsoft.AspNetCore.Mvc;
using music.Models;
using System.Collections.Generic;


namespace music.Controllers
{
    public class MusicController : Controller
    {
        public IActionResult Index()
        {
            var model = new PlaylistViewModel
            {
                Name = "Favorites",
                Tracks = new SampleTracks().GetAllTracks()
            };

            ViewData["Title"] = "Playlist";
            return View(model);
        }
        public IActionResult Grid()
        {
            var model = new PlaylistViewModel
            {
                Name = "Favorites",
                Tracks = new SampleTracks().GetAllTracks()
            };

            ViewData["Title"] = "Playlist";
            return View(model);
        }
    }
}

Views/Music/Grid.cshtml
@model PlaylistViewModel

<div class="container">
    <h2>@ViewData["Title"]</h2>
    <div class="btn-group">
        <a class="btn btn-default" role="button" asp-area="" asp-controller="Music" asp-action="Index">List view</a>
        <button type="button" class="btn btn-default active">Grid view</button>
    </div>
    <p>My awesome music page</p>
    <div class="row display-flex">
        @foreach(var track in @Model.Tracks){
            <div class="col-md-3">
                <div class="well">
                    <h2>@track.Title</h2>
                    <small><h4>@track.Artist</h4></small>
                    <p>Plays: @track.NumPlays</p>
                </div>
            </div>    
        }
    </div>
</div>

Views/Music/Index.cshtml
@model PlaylistViewModel

<img src="~/images/playlistbanner.png" alt="ASP.NET" class="img-responsive" />
<div class="container">
    <h2>@ViewData["Title"]</h2>
        <div class="btn-group">
        <button type="button" class="btn btn-default active">List view</button>
        <a class="btn btn-default" role="button" asp-area="" asp-controller="Music" asp-action="Grid">Grid view</a>
    </div>
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Plays</th>
      </tr>
    </thead>
    <tbody>
        @foreach(var track in @Model.Tracks){
            <tr>
                <td>@track.Title</td>
                <td>@track.Artist</td>
                <td>@track.NumPlays</td>
            </tr>
        }
    </tbody>
  </table>
</div>